//! Static type metadata and include-path validation.
//!
//! [`TypeInfo`] holds compile-time metadata about a resource type: its wire name,
//! field names, and relationship targets. [`TypeRegistry`] collects these and
//! provides [`validate_include_paths()`](TypeRegistry::validate_include_paths)
//! to verify that dot-separated include paths are traversable through the
//! relationship graph.

/// Static metadata about a JSON:API resource type.
/// Generated by the `#[derive(JsonApi)]` macro.
///
/// Marked `#[non_exhaustive]`: construct via [`TypeInfo::new`] so that
/// additional metadata fields can be added without a breaking change.
#[non_exhaustive]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct TypeInfo {
    /// The JSON:API type string (e.g. "articles").
    pub type_name: &'static str,
    /// Attribute and relationship wire names.
    pub field_names: &'static [&'static str],
    /// Relationship name to target type string pairs.
    pub relationships: &'static [(&'static str, &'static str)],
    /// Wire names of attributes the consumer's struct declared as required
    /// (non-`Option`, non-`Vec`). Used by
    /// [`Document::from_str`](crate::Document::from_str) and friends to
    /// surface [`Error::MissingAttribute`](crate::Error::MissingAttribute).
    /// Empty for the dynamic [`Resource`](crate::Resource) and for any
    /// manual `TypeInfo::new(...)` caller that does not opt in via
    /// [`with_required_attributes`](Self::with_required_attributes).
    pub required_attribute_names: &'static [&'static str],
}

impl TypeInfo {
    /// Build a [`TypeInfo`]. Intended for use by `#[derive(JsonApi)]`-generated
    /// code and by manual [`ResourceObject`] impls.
    ///
    /// Defaults `required_attribute_names` to an empty slice. Callers that
    /// care about the [`Error::MissingAttribute`](crate::Error::MissingAttribute)
    /// pre-pass should chain
    /// [`with_required_attributes`](Self::with_required_attributes).
    #[must_use]
    pub const fn new(
        type_name: &'static str,
        field_names: &'static [&'static str],
        relationships: &'static [(&'static str, &'static str)],
    ) -> Self {
        Self {
            type_name,
            field_names,
            relationships,
            required_attribute_names: &[],
        }
    }

    /// Attach the set of attribute wire names the consumer's struct declared
    /// as required (non-`Option`, non-`Vec`). Returns the same [`TypeInfo`]
    /// with the field set; intended to be chained on top of [`new`](Self::new).
    #[must_use]
    pub const fn with_required_attributes(
        mut self,
        names: &'static [&'static str],
    ) -> Self {
        self.required_attribute_names = names;
        self
    }
}

use crate::model::ResourceObject;
use std::collections::HashMap;

/// A registry of static type metadata for include-path validation.
///
/// Populated once at application startup via [`register()`](Self::register)
/// (using derive-generated [`TypeInfo`]) or [`register_info()`](Self::register_info)
/// (manual). Use [`validate_include_paths()`](Self::validate_include_paths)
/// to check that include paths are valid relationship traversals.
#[derive(Debug)]
pub struct TypeRegistry {
    types: HashMap<String, TypeInfo>,
}

impl TypeRegistry {
    /// Create an empty type registry.
    #[must_use]
    pub fn new() -> Self {
        Self {
            types: HashMap::new(),
        }
    }

    /// Register a type using its [`ResourceObject::type_info()`] implementation.
    pub fn register<T: ResourceObject>(&mut self) -> &mut Self {
        let info = T::type_info();
        self.types.insert(info.type_name.to_string(), info);
        self
    }

    /// Register a [`TypeInfo`] directly.
    pub fn register_info(&mut self, info: TypeInfo) -> &mut Self {
        self.types.insert(info.type_name.to_string(), info);
        self
    }

    /// Look up the [`TypeInfo`] for a type name.
    #[must_use]
    pub fn get(&self, type_name: &str) -> Option<&TypeInfo> {
        self.types.get(type_name)
    }

    /// Validate include paths against the registered type graph.
    ///
    /// Each path is dot-separated (e.g. `"comments.author"`). Walks hop-by-hop
    /// through relationship targets. Terminal hops don't require the target type
    /// to be registered.
    #[must_use = "validation result should be used"]
    pub fn validate_include_paths(&self, root_type: &str, paths: &[&str]) -> crate::Result<()> {
        for path in paths {
            if path.is_empty() {
                continue;
            }
            let segments: Vec<&str> = path.split('.').collect();
            let mut current_type = root_type;

            for segment in &segments {
                let info = self.types.get(current_type).ok_or_else(|| {
                    crate::Error::InvalidIncludePath {
                        path: path.to_string(),
                        segment: segment.to_string(),
                        type_name: current_type.to_string(),
                    }
                })?;

                let target = info
                    .relationships
                    .iter()
                    .find(|(name, _)| name == segment)
                    .map(|(_, target)| *target);

                match target {
                    Some(target_type) => {
                        current_type = target_type;
                    }
                    None => {
                        return Err(crate::Error::InvalidIncludePath {
                            path: path.to_string(),
                            segment: segment.to_string(),
                            type_name: current_type.to_string(),
                        });
                    }
                }
            }
        }
        Ok(())
    }
}

impl Default for TypeRegistry {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{Resource, ResourceObject};

    #[test]
    fn test_type_info_default() {
        let info = Resource::type_info();
        assert_eq!(info.type_name, "");
        assert_eq!(info.field_names, &[] as &[&str]);
        assert_eq!(info.relationships, &[] as &[(&str, &str)]);
    }

    #[test]
    fn test_registry_register_and_get() {
        let mut registry = TypeRegistry::new();
        registry.register_info(
            TypeInfo::new(
                "articles",
                &["title", "body", "author"],
                &[("author", "people")],
            ),
        );
        let info = registry.get("articles").unwrap();
        assert_eq!(info.type_name, "articles");
        assert_eq!(info.field_names, &["title", "body", "author"]);
        assert_eq!(info.relationships, &[("author", "people")]);
    }

    #[test]
    fn test_registry_get_missing() {
        let registry = TypeRegistry::new();
        assert!(registry.get("nonexistent").is_none());
    }

    #[test]
    fn test_registry_register_generic() {
        let mut registry = TypeRegistry::new();
        registry.register::<Resource>();
        let info = registry.get("").unwrap();
        assert_eq!(info.field_names, &[] as &[&str]);
    }

    #[test]
    fn test_validate_single_hop_path() {
        let mut registry = TypeRegistry::new();
        registry.register_info(TypeInfo::new(
            "articles",
            &["title", "author"],
            &[("author", "people")],
        ));
        assert!(
            registry
                .validate_include_paths("articles", &["author"])
                .is_ok()
        );
    }

    #[test]
    fn test_validate_multi_hop_path() {
        let mut registry = TypeRegistry::new();
        registry.register_info(TypeInfo::new(
            "articles",
            &["title", "comments"],
            &[("comments", "comments")],
        ));
        registry.register_info(TypeInfo::new(
            "comments",
            &["body", "author"],
            &[("author", "people")],
        ));
        assert!(
            registry
                .validate_include_paths("articles", &["comments.author"])
                .is_ok()
        );
    }

    #[test]
    fn test_validate_invalid_path() {
        let mut registry = TypeRegistry::new();
        registry.register_info(TypeInfo::new("articles", &["title"], &[]));
        let err = registry
            .validate_include_paths("articles", &["nonexistent"])
            .unwrap_err();
        match err {
            crate::Error::InvalidIncludePath {
                path,
                segment,
                type_name,
            } => {
                assert_eq!(path, "nonexistent");
                assert_eq!(segment, "nonexistent");
                assert_eq!(type_name, "articles");
            }
            other => panic!("expected InvalidIncludePath, got: {other}"),
        }
    }

    #[test]
    fn test_validate_unknown_root_type() {
        let registry = TypeRegistry::new();
        let err = registry
            .validate_include_paths("unknown", &["author"])
            .unwrap_err();
        match err {
            crate::Error::InvalidIncludePath { type_name, .. } => {
                assert_eq!(type_name, "unknown");
            }
            other => panic!("expected InvalidIncludePath, got: {other}"),
        }
    }

    #[test]
    fn test_validate_terminal_hop_unregistered_target() {
        let mut registry = TypeRegistry::new();
        registry.register_info(TypeInfo::new(
            "articles",
            &["title", "author"],
            &[("author", "people")],
        ));
        // "people" is NOT registered, but "author" is the terminal hop — should pass
        assert!(
            registry
                .validate_include_paths("articles", &["author"])
                .is_ok()
        );
    }

    #[test]
    fn test_validate_intermediate_hop_unregistered_target() {
        let mut registry = TypeRegistry::new();
        registry.register_info(TypeInfo::new(
            "articles",
            &["title", "author"],
            &[("author", "people")],
        ));
        // "people" is NOT registered, but "author.name" tries to traverse through it
        let err = registry
            .validate_include_paths("articles", &["author.name"])
            .unwrap_err();
        match err {
            crate::Error::InvalidIncludePath {
                segment, type_name, ..
            } => {
                assert_eq!(segment, "name");
                assert_eq!(type_name, "people");
            }
            other => panic!("expected InvalidIncludePath, got: {other}"),
        }
    }

    #[test]
    fn test_validate_empty_path_skipped() {
        let registry = TypeRegistry::new();
        assert!(registry.validate_include_paths("articles", &[""]).is_ok());
    }

    #[test]
    fn test_validate_multiple_paths() {
        let mut registry = TypeRegistry::new();
        registry.register_info(TypeInfo::new(
            "articles",
            &["title", "author", "tags"],
            &[("author", "people"), ("tags", "tags")],
        ));
        assert!(
            registry
                .validate_include_paths("articles", &["author", "tags"])
                .is_ok()
        );
    }

    #[test]
    fn test_type_info_default_required_attributes_empty() {
        let info = Resource::type_info();
        assert_eq!(info.required_attribute_names, &[] as &[&str]);
    }

    #[test]
    fn test_type_info_with_required_attributes_round_trip() {
        let info = TypeInfo::new("articles", &["title", "body"], &[])
            .with_required_attributes(&["title"]);
        assert_eq!(info.required_attribute_names, &["title"]);
        assert_eq!(info.type_name, "articles");
        assert_eq!(info.field_names, &["title", "body"]);
    }

    #[test]
    fn test_required_attribute_names_round_trip_through_register_info() {
        let mut registry = TypeRegistry::new();
        registry.register_info(
            TypeInfo::new("articles", &["title"], &[]).with_required_attributes(&["title"]),
        );
        let info = registry.get("articles").unwrap();
        assert_eq!(info.required_attribute_names, &["title"]);
    }
}
